// Datos para las diferentes vistas de la apertura
const apertureAngles = {
    'vicerrector': {
        image: './assets/img/AperturaVicerrector.jpg'
    },
    'organizador': {
        image: './assets/img/AperturaSamuel.jpg'
    },
    'himno': {
        image: './assets/img/SamuelHimno.jpg',
    }
};

                                                                                                // Datos para el grupo folklórico
                                                                                                const folkloreAngles = {
                                                                                                    'instruments': {
                                                                                                            image: '/images/festival/folklorico/folklorico-instrumentos-wide.jpg',
                                                                                                                    description: 'El grupo folklórico explicando las diferencias entre instrumentos tradicionales y sus orígenes culturales.'
                                                                                                                        },
                                                                                                                            'dance': {
                                                                                                                                    image: '/images/festival/folklorico/folklorico-danza-wide.jpg',
                                                                                                                                            description: 'Los integrantes del grupo ejecutando una danza tradicional en perfecta sincronía.'
                                                                                                                                                },
                                                                                                                                                    'public': {
                                                                                                                                                            image: '/images/festival/folklorico/folklorico-publico-wide.jpg',
                                                                                                                                                                    description: 'Momento interactivo donde el público se unió a la presentación bailando junto a los artistas.'
                                                                                                                                                                        },
                                                                                                                                                                            'solo': {
                                                                                                                                                                                    image: '/images/festival/folklorico/folklorico-solista-wide.jpg',
                                                                                                                                                                                            description: 'Primer plano de un músico solista demostrando la técnica de un instrumento específico.'
                                                                                                                                                                                                }
                                                                                                                                                                                                };

                                                                                                                                                                                                // Mapeo de galerías a sus elementos HTML
                                                                                                                                                                                                const galleryElements = {
                                                                                                                                                                                                    'apertura': {
                                                                                                                                                                                                            mainImage: 'mainImageApertura',
                                                                                                                                                                                                                    description: 'descriptionApertura'
                                                                                                                                                                                                                        },
                                                                                                                                                                                                                            'folklorico': {
                                                                                                                                                                                                                                    mainImage: 'mainImageFolklorico',
                                                                                                                                                                                                                                            description: 'descriptionFolklorico'
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                // Mapeo de galerías a sus datos
                                                                                                                                                                                                                                                const galleryData = {
                                                                                                                                                                                                                                                    'apertura': apertureAngles,
                                                                                                                                                                                                                                                        'folklorico': folkloreAngles
                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                        function changeAngle(galleryType, angle, element) {
                                                                                                                                                                                                                                                            // Actualizar botones activos
                                                                                                                                                                                                                                                                const buttons = element.parentElement.querySelectorAll('.angle-option');
                                                                                                                                                                                                                                                                    buttons.forEach(btn => btn.classList.remove('active'));
                                                                                                                                                                                                                                                                        element.classList.add('active');

                                                                                                                                                                                                                                                                            // Obtener elementos HTML
                                                                                                                                                                                                                                                                                const mainImageId = galleryElements[galleryType].mainImage;
                                                                                                                                                                                                                                                                                    const descriptionId = galleryElements[galleryType].description;
                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                            const mainImage = document.getElementById(mainImageId);
                                                                                                                                                                                                                                                                                                const description = document.getElementById(descriptionId);
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                        // Obtener datos de la imagen
                                                                                                                                                                                                                                                                                                            const imageData = galleryData[galleryType][angle];
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                    // Aplicar cambios
                                                                                                                                                                                                                                                                                                                        mainImage.style.backgroundImage = `url('${imageData.image}')`;
                                                                                                                                                                                                                                                                                                                            description.textContent = imageData.description;
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                    // Efecto visual de transición
                                                                                                                                                                                                                                                                                                                                        mainImage.style.opacity = '0.7';
                                                                                                                                                                                                                                                                                                                                            setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                    mainImage.style.opacity = '1';
                                                                                                                                                                                                                                                                                                                                                        }, 150);
                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                        // Inicializar galerías con la primera imagen
                                                                                                                                                                                                                                                                                                                                                        document.addEventListener('DOMContentLoaded', function() {
                                                                                                                                                                                                                                                                                                                                                            // Inicializar galería de apertura
                                                                                                                                                                                                                                                                                                                                                                const aperturaInitial = apertureAngles.stage;
                                                                                                                                                                                                                                                                                                                                                                    const mainImageApertura = document.getElementById('mainImageApertura');
                                                                                                                                                                                                                                                                                                                                                                        mainImageApertura.style.backgroundImage = `url('${aperturaInitial.image}')`;
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                // Inicializar galería folklórica
                                                                                                                                                                                                                                                                                                                                                                                    const folkloricoInitial = folkloreAngles.instruments;
                                                                                                                                                                                                                                                                                                                                                                                        const mainImageFolklorico = document.getElementById('mainImageFolklorico');
                                                                                                                                                                                                                                                                                                                                                                                            mainImageFolklorico.style.backgroundImage = `url('${folkloricoInitial.image}')`;
                                                                                                                                                                                                                                                                                                                                                                                            });